PolyAppart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myapp.urls")),
    #path("carapide/", include("carapide.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('',accueil,name="accueil"),
    path('inscription_proprietaire',Proprietaire_reregister,name="inscription_proprietaire"),
    path('ajouter_appartement',ajouter_appartement_,name="ajouter_appartement"),
    path('appartement/<int:appartement_id>/', detail_appartement, name='detail_appartement'),
    path('profil/<int:props_id>/', visit_profil, name='visit_profil'),
    path('Proprietaire_login/', Proprietaire_login, name='Proprietaire_login'),
    path('profil/', profil, name='profil'),
    path('logout/', LogoutView.as_view(next_page='accueil'), name='logout'),
    path('signe_log/',view_signe_log,name="signe_log"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
# Create your models here.


class Utilisateur(User):
    nom = models.CharField(max_length=30)
    telephone = models.CharField(max_length=30)

    def __str__(self):
        return self.nom
    
    class Meta:
        db_table = "Utilisateur"
        verbose_name = 'Utilisateur'
        verbose_name_plural = "Utilisateurs"
        
        
class Proprietaire(User):
    nom = models.CharField(max_length=30)
    telephone = models.CharField(max_length=20)
    profil_photo = models.ImageField(upload_to='Profil_Proprietaire/', default = "")
    licence = models.CharField(max_length=30, default = "")
    Taxe_Number = models.CharField(max_length=30, default = "")
    Specialite = models.CharField(max_length=30, default = "")
    # Autres champs spécifiques au propriétaire

    def __str__(self):
        return self.nom
    
    class Meta:
        db_table = "Proprietaire" 
        verbose_name = 'Proprietaire'
        verbose_name_plural = "Proprietaires"
        

class Appartement(models.Model):
    proprietaire = models.ForeignKey(Proprietaire, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100, default="")
    ville = models.CharField(max_length=100)
    adresse = models.CharField(max_length=100)
    profil_photo = models.ImageField(upload_to='Profil_Appartement/', default="")
    taille = models.CharField(max_length=100)
    nombre_chambres = models.CharField(max_length=100)
    salle_de_bain = models.CharField(max_length=100 ,default="")
    garrage = models.CharField(max_length=100,default="")
    prix = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.adresse
        


class ImageAppartement(models.Model):
    appartement = models.ForeignKey(Appartement, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='appartements/')
    # Autres champs spécifiques à l'image

    def __str__(self):
        return self.image.name


class Reservation(models.Model):
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    appartement = models.ForeignKey(Appartement, on_delete=models.CASCADE)
    date_debut = models.DateField()
    date_fin = models.DateField()
    montant_paye = models.DecimalField(max_digits=10, decimal_places=2)
    # Autres champs spécifiques à la réservation

    def __str__(self):
        return f"{self.utilisateur.username} - {self.appartement.adresse}"
    
    

class Message(models.Model):
    expediteur_name = models.CharField(max_length=100 , default="")
    expediteur_email = models.EmailField(default="")
    expediteur_phone = models.CharField(max_length=100, default="")
    destinataire = models.ForeignKey(Proprietaire, on_delete=models.CASCADE, related_name='messages_recus')
    appartement = models.ForeignKey(Appartement, on_delete=models.CASCADE, default="")
    #reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    contenu = models.TextField()
    date_envoi = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"De: {self.expediteur_name} à: {self.destinataire}"

templates/accueil.html
{% extends 'base.html' %}

{% block content %}


{% load static %}

<div class="banner">
    <h1>Find Your Perfect Home</h1>
    <p>Take Control and find your dream home today. We buy and sell more than 1000 properties and serve all of the world. Take a look at our selection</p>
</div>

   
<div class="after_banner">
  Découvrez Nos Plus Belles Appartement
  <p class="after_banner_1">Trouver L'appartement Idéale pour Vous </p>
</div>


<div class="articles_block">
    <div class="row">
    {% for appartement in appartements %}
      <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="article">
          <a href="{% url 'detail_appartement' appartement.id %}">
            <div class="card">
              <div class="card text-bg-primary">
                <div class="x"><img src="{{ appartement.profil_photo.url }}" class="card-img" alt="..."></div>
                <div class="card-img-overlay">
                  <h4 class="card-title prix">{{ appartement.prix }} Fcfa / Mois</h4>
                </div>
              </div>
              <div class="card-body">
                <p class="card-title nom"> {{ appartement.nom }} </p>
                <p class="card-text adresse">{{ appartement.adresse }}</p>
                <div class="device">
                  <div style="margin-right: 20px;"> <i style="font-size: 20px;" class="fa-solid fa-bed"></i> {{ appartement.nombre_chambres }} </div>
                  <div style="margin-right: 20px;"> <i style="font-size: 20px;" class="fa-solid fa-bath"></i> {{ appartement.salle_de_bain }} </div>
                  <div style="margin-right: 20px;"> <i style="font-size: 20px;" class="fa-solid fa-car"></i> {{ appartement.garrage }} </div>
                   
                </div>
                <div>
                  <hr>
                  <span class="props"> <i style="font-size: 15px;" class="fa-regular fa-user"></i> <a class="props" href="{% url 'visit_profil' appartement.proprietaire.id %}">{{ appartement.proprietaire.nom }}</a> </span>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>

    {% endfor %}
  </div>
</div>


<div class="after_banner">
  Rencontrez Nos Agents
  <p class="after_banner_1">Discutez Avec Eux Ou Appellez Les ! </p>
</div>

<div class="Agents">

  <div class="row row1">
    {% for proprietaire in proprietaires %}
      <div class="col-xs-12 col-sm-12 col-md-3">

        <div style="width: 200px ;margin: auto;">
          <img style="width: 200px; height: 200px; border-radius: 50%;" src="{{ proprietaire.profil_photo.url }}" class="card-img" alt="...">
        </div>

        <div style="width: 60%; margin: auto; text-align: center; margin-top: 20px;">
          <h6 style="color: #007BFF; font-weight: 700;">{{ proprietaire.nom }}</h6>
          <h6 style="font-weight: 600;">Company Agent, Sénégal</h6>
          <h6 style="font-weight: 600;">{{ proprietaire.Specialite }}</h6>
          <p style="margin-top: 30px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta justo eget risus consectetur,...</p> <br>
          <a href="{% url 'visit_profil' proprietaire.id %}"><h6 style="font-weight: 600;">Visit Profil</h6></a> <br>
        </div>
        
      </div>

    {% endfor %}
  </div>

</div>


<div class="after_banner">
  Les Témoignage Sur Nous
  <p class="after_banner_1">Lorem ipsum dolor sit amet, consectetur adipisicing elit </p>
</div>

<div class="row Temoignage">

  <div class="col-sm-12 col-md-4 Tem">
    <div>
      <i class="fa-regular fa-quote-left"></i><br>
      <div style="margin-bottom: 30px;">
        <h4>Mouhamed Gueye</h4><br>
        Lorem ipsum dolor sit amet, consectetur <br>
        adipiscing elit, sed do eiusmod tempor <br>
        incididunt ut labore et dolore magna <br>
        aliqua. 
      </div>
      <div style="height: 100px;width: 100px; margin: auto;">
        <img style="width: 100px; height: 100px; border-radius: 50%; margin: auto;" src="/static/img/mg.jpeg" class="card-img" alt="...">
      </div>      
    </div>

  </div>

  <div class="col-sm-12 col-md-4 Tem">
    <div>
      <i class="fa-regular fa-quote-left"></i>
      <div style="margin-bottom: 30px;">
        <h4>Aimerou Ndiaye</h4><br>
        Lorem ipsum dolor sit amet, consectetur <br>
        adipiscing elit, sed do eiusmod tempor <br>
        incididunt ut labore et dolore magna <br>
        aliqua. 
      </div>
      <div style="height: 100px;width: 100px; margin: auto;">
        <img style="width: 100px; height: 100px; border-radius: 50%; margin: auto;" src="/static/img/aimerou.jpeg" class="card-img" alt="...">
      </div>      
    </div>

  </div>

  <div class="col-sm-12 col-md-4 Tem">
    <div>
      <i class="fa-regular fa-quote-left"></i>
      <div style="margin-bottom: 30px;">
        <h4>Djibril Diallo</h4><br>
        Lorem ipsum dolor sit amet, consectetur <br>
        adipiscing elit, sed do eiusmod tempor <br>
        incididunt ut labore et dolore magna <br>
        aliqua. 
      </div>
      <div style="height: 100px;width: 100px; margin: auto;">
        <img style="width: 100px; height: 100px; border-radius: 50%; margin: auto;" src="/static/img/djibril.jpeg" class="card-img" alt="...">
      </div>      
    </div>

  </div>


</div>




{% endblock content %}

templates/accueil1.html
{% extends 'base.html' %}

{% block content %}


{% load static %}

<div class="banner">
    <h1>Find Your Perfect Home</h1>
    <p>Take Control and find your dream home today. We buy and sell more than 1000 properties and serve all of the world. Take a look at our selection</p>
</div>

   
<div class="after_banner">
  Découvrez Nos Plus Belles Appartement
  <p class="after_banner_1">Trouver L'appartement Idéale pour Vous </p>
</div>


<div class="articles_block">
    <div class="row">
    {% for appartement in appartements %}
      <div class="col-md-4">
        <div class="article">
          <a href="{% url 'detail_appartement' appartement.id %}">
            <div class="card">
              <div class="card text-bg-primary">
                <div class="x"><img src="{{ appartement.profil_photo.url }}" class="card-img" alt="..."></div>
                <div class="card-img-overlay">
                  <h4 class="card-title prix">{{ appartement.prix }} Fcfa / Mois</h4>
                </div>
              </div>
              <div class="card-body">
                <p class="card-title nom"> {{ appartement.nom }} </p>
                <p class="card-text adresse">{{ appartement.adresse }}</p>
                <div class="device">
                  <div><i style="font-size: 20px;" class="fa-solid fa-bed"></i> {{ appartement.nombre_chambres }}</div>
                  <div><i style="font-size: 20px;" class="fa-solid fa-bath"></i> {{ appartement.salle_de_bain }}</div>
                  <div><i style="font-size: 20px;" class="fa-solid fa-car"></i> {{ appartement.garrage }}</div>
                   
                </div>
                <div>
                  <hr>
                  <span class="props"> <i style="font-size: 15px;" class="fa-regular fa-user"></i> <a class="props" href="{% url 'visit_profil' appartement.proprietaire.id %}">{{ appartement.proprietaire.nom }}</a> </span>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      {% if forloop.counter|divisibleby:3 %}
        </div><div class="row">
      {% endif %}
    {% endfor %}
  </div>
</div>


<div class="after_banner">
  Rencontrez Nos Agents
  <p class="after_banner_1">Discutez Avec Eux Ou Appellez Les ! </p>
</div>

<div class="Agents">

  <div class="row1">
    {% for proprietaire in proprietaires %}
      <div>

        <div style="width: 200px ;margin: auto;">
          <img style="width: 200px; height: 200px; border-radius: 50%;" src="{{ proprietaire.profil_photo.url }}" class="card-img" alt="...">
        </div>

        <div style="width: 60%; margin: auto; text-align: center; margin-top: 20px;">
          <h6 style="color: #007BFF; font-weight: 700;">{{ proprietaire.nom }}</h6>
          <h6 style="font-weight: 600;">Company Agent, Sénégal</h6>
          <h6 style="font-weight: 600;">{{ proprietaire.Specialite }}</h6>
          <p style="margin-top: 30px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta justo eget risus consectetur,...</p> <br>
          <a href="{% url 'visit_profil' proprietaire.id %}"><h6 style="font-weight: 600;">Visit Profil</h6></a> <br>
        </div>
        
      </div>
      {% if forloop.counter|divisibleby:4 %}
        </div><div class="row1">
      {% endif %}
    {% endfor %}
  </div>

</div>


<div class="after_banner">
  Les Témoignage Sur Nous
  <p class="after_banner_1">Lorem ipsum dolor sit amet, consectetur adipisicing elit </p>
</div>

<div class="Temoignage">

  <div class="Tem">
    <i class="fa-regular fa-quote-left"></i>
    <div>
      Lorem ipsum dolor sit amet, consectetur <br>
      adipiscing elit, sed do eiusmod tempor <br>
      incididunt ut labore et dolore magna <br>
      aliqua. 
    </div>
    <div>
      <img class="tem_img" src="" alt="">
    </div>
  </div>

  <div class="Tem">
    <i class="fa-regular fa-quote-left"></i>
    <div>
      Lorem ipsum dolor sit amet, consectetur <br>
      adipiscing elit, sed do eiusmod tempor <br>
      incididunt ut labore et dolore magna <br>
      aliqua. 
    </div>
    <div>
      <img class="tem_img" src="" alt="">
    </div>
  </div>

  <div class="Tem">
    <i class="fa-regular fa-quote-left"></i>
    <div>
      Lorem ipsum dolor sit amet, consectetur <br>
      adipiscing elit, sed do eiusmod tempor <br>
      incididunt ut labore et dolore magna <br>
      aliqua. 
    </div>
    <div>
      <img class="tem_img" src="" alt="">
    </div>
  </div>


</div>




{% endblock content %}

templates/ajouter_appartement.html
{% extends 'base.html' %}

{% block content %}
  
{% load static %}


<div class="row ajout_app">

  <div class="col-sm-12 col-md-6 ajout_app_containt">

    <form method="POST" action="{% url 'ajouter_appartement' %}" enctype="multipart/form-data" class="ajout_app_form">
      {% csrf_token %}

      <h3>Ajouter Votre Appartement</h3>
      <div id="trait"></div>

      <div>
        <label for="id_username">Ville</label>
        <input placeholder="Veuillez entrer la ville" type="text" name="ville" id="ville" class="form-control" required>
      </div>

      <div>
        <label for="id_username">Adresse exacte</label>
        <input placeholder="Adress" type="text" name="adresse" id="adresse" class="form-control" required>
      </div>

      <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
        <div>
          <label for="prix">Nom</label>
          <input placeholder="Nom" type="text" name="nom" id="nom" class="form-control" required>
        </div>

        <div>
          <label for="prix">Prix :</label>
          <input placeholder="Prix" type="number" name="prix" id="prix" class="form-control" required>
        </div>
      </div>

      <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
        <div>
          <label for="taille">Taille en M²</label>
          <input placeholder="Veuillez entrer la taille" type="text" name="taille" id="taille" class="form-control" required>
        </div>

        <div>
          <label for="id_telephone">Nombre de Chambre </label>
          <input placeholder="Nombre de chambre" type="text" name="nombre_chambres" id="id_telephone" class="form-control" required>
        </div>

      </div>

      <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
        <div>
          <label for="salle de bain">Nombre de Salle de Bain</label>
          <input placeholder="Veuillez entrer la taille" type="text" name="salle_de_bain" id="salle_de_bain" class="form-control" required>
        </div>

        <div>
          <label for="id_telephone">Nombre de garage </label>
          <input placeholder="Nombre de garage" type="text" name="garrage" id="garrage" class="form-control" required>
        </div>

      </div>

      <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
        <div>
          <label for="photo_profil"> Photo de Couverture  :</label>
          <input type="file" id="profil_photo" name="profil_photo" class="form-control">
        </div>

        <div>
          <label for="photo_profil">Ajoutez Des Images :</label>
          <input type="file" name="images" multiple class="form-control">
        </div>
      </div>

      <div class="form-group">
        <label for="description">Mettez une description a votre appartement</label>
        <textarea name="description" cols="60" rows="10" class="form-control"></textarea>
      </div> 

      <div>
        <button class="btn btn_ajouter" type="submit">Ajouter</button>
      </div>
    
    </form>   
  </div>


</div>

    
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

    <link rel="stylesheet" href=" {% static 'css/style.css' %} ">
    <title>acceuil</title>
</head>

<body>

    {% block header %}
    {% include "head.html" %}
    {% endblock header %}

    {% block content %}

    {% endblock content %}

    {% block footer %}
    {% include "foot.html" %}
    {% endblock footer %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

templates/detail_appartement.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div style="background-color: #F7F8F9;">

<div class="detail_appartement">

  <div class="row nom_prix">
    <div class="col-sm-12 col-md-6">{{ appartement.nom }}</div>
    <div class="col-sm-12 col-md-6">{{ appartement.prix }} Fcfa / Mois</div>
  </div>

  <div style="margin-top: 20px; margin-bottom: 20px;" >
    <i style="font-size: 20px;" class="fa-solid fa-location-dot"></i> {{ appartement.adresse }}
  </div>

  <div class="row det_app">
    <div class="col-sm-12 col-md-8 detail">

      <div>
        <img src="{{ appartement.profil_photo.url }}" class="card-img" alt="...">
      </div>

      <div class="devices">
        <span style="font-size: 20px; font-weight: 700;">Details </span>
        <hr>
        <div class="row">
          <div class="col-sm-6 col-md-3"><i style="font-size: 20px;" class="fa-solid fa-bed"></i> <span style="color: black;"> {{ appartement.nombre_chambres }}</span>  <br> Chambre</div>
          <div class="col-sm-6 col-md-3"><i style="font-size: 20px;" class="fa-solid fa-bath"></i> <span style="color: black;"> {{ appartement.salle_de_bain }} </span> <br> Salle de Bain</div>
          <div class="col-sm-6 col-md-3"><i style="font-size: 20px;" class="fa-solid fa-car"></i> <span style="color: black;"> {{ appartement.garrage }}</span>  <br> Garage</div>
          <div class="col-sm-6 col-md-3"><i class="fa-sharp fa-solid fa-apartment"></i><span style="color: black;">{{ appartement.taille }} M² </span> <br> Taille </div>          
        </div>

      </div>

      <div class="describe">
        <span style="font-size: 20px; font-weight: 700;">desscription</span>
        <hr>
        {{ appartement.description }}
      </div>

      <div class="adresse_">
        <span style="font-size: 20px; font-weight: 700;color: black;">Adresse</span>
        <hr>
        <div>
          <div style="display: flex; justify-content: space-between;"><div style="color: black; font-size: 16px; font-weight: 700;">Adress</div> <div>{{ appartement.adresse }}</div> </div>
          <hr>
          <div style="display: flex; justify-content: space-between;"><div style="color: black; font-size: 16px; font-weight: 700;">Ville</div> <div>{{ appartement.ville }}</div> </div>          
        </div>

      </div>
      
      
    </div>

    <div class="col-sm-12 col-md-4 contact">

      <div class="proprietaire_profil">
        <div class="card mb-3" style="max-width: 540px; border: none;">
          <div class="row g-0">
            <div class="col-sm-12 col-md-12">
              <img src="{{ appartement.proprietaire.profil_photo.url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-sm-12 col-md-12 mb-3" >
              <div class="card-body">
                <p style="font-weight: 700;" class="card-title">{{ appartement.proprietaire.nom }}</p> 
                <a href="{% url 'visit_profil' appartement.proprietaire.id %}">Voir Le Profil</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <form method="POST" action="{% url 'detail_appartement' appartement.id %}">
        {% csrf_token %}

        <div class="form-group"> 
          <input placeholder="Nom" type="text" name="Nom" id="id_Nom" class="form-control" required>
        </div>

        <div class="form-group">
          <input placeholder="Email" type="email" name="email" id="id_email" class="form-control" required>
        </div>

        <div class="form-group">
          <input placeholder="Phone" type="text" name="telephone" id="id_telephone" class="form-control" required>
        </div>   

        <div class="form-group">
          <textarea style="margin-left: 0px; width: 100%;" name="contenu" cols="27" rows="4"></textarea>
        </div>   

        <div style="margin-top: 40px;">
          
          <div><button class="btn" type="submit">Send Message</button></div>
          
        </div>
      
      </form>      
    </div>
 
  </div>

</div>

</div>
{% endblock content %}

templates/inscription_Proprietaire.html
{% extends 'base.html' %}

{% block content %}
  
{% load static %}



<div class="row ajout_app">

  <div class="col-sm-12 col-md-6 ajout_app_containt">

    <form method="POST" action="{% url 'inscription_proprietaire' %}" enctype="multipart/form-data" class="ajout_app_form">
      {% csrf_token %}

      <h1>Inscription</h1>
      <div id="trait"></div>

      <div>
        <label for="id_username">Nom complet</label>
        <input placeholder="Veuillez entrer votre nom" type="text" name="Nom" id="id_Nom" class="form-control" required>
      </div>

      <div>
        <label for="id_username">Nom d'utilisateur</label>
        <input placeholder="Veuillez entrer votre username" type="text" name="username" id="id_username" class="form-control" required>
      </div>

      <div>
        <label for="id_email">Email</label>
        <input placeholder="Veuillez entrer votre email" type="email" name="email" id="id_email" class="form-control" required>
      </div>

      <div>
        <label for="id_telephone">Numéro de téléphone</label>
        <input placeholder="Veuillez entrer votre tel" type="text" name="telephone" id="id_telephone" class="form-control" required>
      </div>

      <div>
        <label for="id_password1">Mot de passe</label>
        <input placeholder="Veuillez entrer votre mdp" type="password" name="password1" id="id_password1" class="form-control" required>
      </div>

      <div>
        <label for="id_password2">Confirmation mot de passe</label>
        <input placeholder="Veuillez confirmer votre email" type="password" name="password2" id="id_password2" class="form-control" required>
      </div>

      <div>
        <label for="photo_profil">Photo de profil :</label>
        <input type="file" id="profil_photo" name="profil_photo" class="form-control">
      </div>

      <div>
        <button class="btn btn_ajouter" type="submit">S'inscrire</button>
      </div>

      <div id="option">
        Vous avez déjà un compte ? <a href="{% url 'Proprietaire_login' %}" style="margin-left: 10px;"> Connectez-vous </a>
        </div>
    
    </form>   
  </div>


</div>


  
{% endblock content %}

templates/message_proprietaire.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<form method="POST" action="{% url 'ajouter_appartement' %}" enctype="multipart/form-data">
  {% csrf_token %}

<div class="d-flex flex-row justify-content-around align-items-center ins1_page">
<div>
  <h1>Inscription</h1>
  <div id="trait"></div>
  <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
    <div>
      <div class="form-group"> 
        <label for="id_username">Dans quel ville se trouve l'appartement</label>
        <input placeholder="Veuillez entrer la ville" type="text" name="ville" id="ville" class="form-control" required>
      </div>
    </div>

    <div>
      <div class="form-group">
        <label for="id_username">Quel est l'adresse exact de l'appartement</label>
        <input placeholder="Adress" type="text" name="adresse" id="adresse" class="form-control" required>
      </div>  
    </div>
  </div>  

  <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
      <div>  
        <div class="form-group">
          <label for="taille">Quel est la taille de l'appartement</label>
          <input placeholder="Veuillez entrer la taille" type="text" name="taille" id="taille" class="form-control" required>
        </div>
      </div>

      <div>
        <div class="form-group">
          <label for="id_telephone">Quel est le nombre de Chambre de l'appartement</label>
          <input placeholder="Nombre de chambre" type="text" name="nombre_chambres" id="id_telephone" class="form-control" required>
        </div>          
      </div>
 
  </div>

  <div class="d-flex flex-row justify-content-between align-items-center ins1_form">
    <div>
        <div class="form-group">
          <label for="prix">Prix :</label>
          <input placeholder="Prix" type="text" name="prix" id="prix" class="form-control" required>
        </div> 
    </div>

    <div>
      <div class="form-group">
        <label for="description">Mettez une description a votre appartement</label>
        <textarea name="description" cols="40" rows="4"></textarea>
      </div>       
    </div>

    <div>
      <div class="form-group">
        <label for="photo_profil"> Photo de Couverture  :</label>
        <input type="file" id="profil_photo" name="profil_photo">
      </div>       
    </div>

    <div>
      <div class="form-group">
        <label for="photo_profil">Ajoutez Des Images Pour votre appartement :</label>
        <input type="file" name="images" multiple>
      </div>       
    </div>



  </div>

</div>

<div style="margin-top: 40px;">
  <img src="{% static 'img/profil.png' %}" alt="" class="profil">
  <div><button class="btn" type="submit">Ajouter <i class="fa-solid fa-chevron-right chevron1"></i></button></div>
  
</div>

</form>  


  
  

  {% endblock content %}